spring:
  application:
    name:Config-Default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultone: http//localhost:8761/eureka
